### ISSUE TITLE
Grade Average Edits for 2 Students

### ISSUE THREAD

**Issue by amason** [jiscdev/uoj#31] opened 2017-01-31 16:39 UTC
@michaelwebbjisc Can you please make the following edits to the blue UDD data:

- For student ID 50419, I need the GAP to be 50.
- For student ID 50681, I need the GPA to be 82.

**Comment by michaelwebbjisc** [comment] 2017-01-31 16:40
Duplicate of #14 and #15

**Closed by michaelwebbjisc** 2017-01-31 16:40 UTC
