### ISSUE TITLE
Personal Tutor Should be NULL in Blue UDD Data for Student ID 50049

### ISSUE THREAD

**Issue by amason** [jiscdev/uoj#28] opened 2017-01-31 16:36 UTC
@michaelwebbjisc 

In the UDD, Caroline Bowman, student ID 50049 should not be assigned a personal tutor. We will have SSP configured to have Beth Kim as the default coach in SSP. Test case is to make sure student id 50049 who came over in the UDD is assigned to the default coach, Beth Kim.

Can you please make this change for me?

**Comment by michaelwebbjisc** [comment] 2017-01-31 16:37
Duplicate of issue #9 ?

**Closed** 2017-01-31 16:40 UTC

**Comment by amason** [comment] 2017-01-31 16:42
Odd - I never received these specific github notifications. You are correct, this is a duplicate. Sorry for the confusion (although I blame this on github notifications) lol 

Amanda
