### ISSUE TITLE
Last Activity Edits for 3 Students

### ISSUE THREAD

**Issue by amason** [jiscdev/uoj#30] opened 2017-01-31 16:38 UTC
@michaelwebbjisc Can you please make the following changes to Last Activity Date:

- For student id 50922, I need the last activity date to be 1/23/2017. 
- For student id 50882, I need the last activity date to be 1/13/2017. 
- For student ID 50985, I need the data to be 12/15/2016.

**Comment by michaelwebbjisc** [comment] 2017-01-31 16:39
Duplicate of issues #11 #12 and #13

**Closed** 2017-01-31 16:40 UTC

**Comment by amason** [comment] 2017-01-31 16:44
Odd - I never received these specific github notifications. You are correct, this is a duplicate. Sorry for the confusion (although I blame this on github notifications) lol

Amanda
